export const EMOJIS = [
	{ emoji: '😀', name: 'Grinning Face' },
	{ emoji: '😃', name: 'Grinning Face with Big Eyes' },
	{ emoji: '😄', name: 'Grinning Face with Smiling Eyes' },
	{ emoji: '😁', name: 'Beaming Face with Smiling Eyes' },
	{ emoji: '😆', name: 'Grinning Squinting Face' },
	{ emoji: '😅', name: 'Grinning Face with Sweat' },
	{ emoji: '🤣', name: 'Rolling on the Floor Laughing' },
	{ emoji: '😂', name: 'Face with Tears of Joy' },
	{ emoji: '🙂', name: 'Slightly Smiling Face' },
	{ emoji: '🙃', name: 'Upside-Down Face' },
	{ emoji: '😉', name: 'Winking Face' },
	{ emoji: '😊', name: 'Smiling Face with Smiling Eyes' },
	{ emoji: '😇', name: 'Smiling Face with Halo' },
	{ emoji: '🥰', name: 'Smiling Face with Hearts' },
	{ emoji: '😍', name: 'Heart Eyes' },
	{ emoji: '🤩', name: 'Star-Struck' },
	{ emoji: '😘', name: 'Face Blowing a Kiss' },
	{ emoji: '😗', name: 'Kissing Face' },
	{ emoji: '😚', name: 'Kissing Face with Closed Eyes' },
	{ emoji: '😙', name: 'Kissing Face with Smiling Eyes' },
	{ emoji: '🥲', name: 'Smiling Face with Tear' },
	{ emoji: '😋', name: 'Face Savoring Food' },
	{ emoji: '😛', name: 'Face with Tongue' },
	{ emoji: '😜', name: 'Winking Face with Tongue' },
	{ emoji: '🤪', name: 'Zany Face' },
	{ emoji: '😝', name: 'Squinting Face with Tongue' },
	{ emoji: '🤑', name: 'Money-Mouth Face' },
	{ emoji: '🤗', name: 'Hugging Face' },
	{ emoji: '🤔', name: 'Thinking Face' },
	{ emoji: '🤐', name: 'Zipper-Mouth Face' },
	{ emoji: '😐', name: 'Neutral Face' },
	{ emoji: '😑', name: 'Expressionless Face' },
	{ emoji: '😶', name: 'Face Without Mouth' },
	{ emoji: '😏', name: 'Smirking Face' },
	{ emoji: '😒', name: 'Unamused Face' },
	{ emoji: '🙄', name: 'Face with Rolling Eyes' },
	{ emoji: '😬', name: 'Grimacing Face' },
	{ emoji: '😌', name: 'Relieved Face' },
	{ emoji: '😔', name: 'Pensive Face' },
	{ emoji: '😪', name: 'Sleepy Face' },
	{ emoji: '🤤', name: 'Drooling Face' },
	{ emoji: '😴', name: 'Sleeping Face' },
	{ emoji: '😷', name: 'Face with Medical Mask' },
	{ emoji: '🤒', name: 'Face with Thermometer' },
	{ emoji: '🤕', name: 'Face with Head-Bandage' },
	{ emoji: '🤢', name: 'Nauseated Face' },
	{ emoji: '🤮', name: 'Face Vomiting' },
	{ emoji: '🤧', name: 'Sneezing Face' },
	{ emoji: '🥵', name: 'Hot Face' },
	{ emoji: '🥶', name: 'Cold Face' },
	{ emoji: '🥴', name: 'Woozy Face' },
	{ emoji: '😵', name: 'Dizzy Face' },
	{ emoji: '🤯', name: 'Exploding Head' },
	{ emoji: '🤠', name: 'Cowboy Hat Face' },
	{ emoji: '🥳', name: 'Partying Face' },
	{ emoji: '😎', name: 'Smiling Face with Sunglasses' },
	{ emoji: '🤓', name: 'Nerd Face' },
	{ emoji: '🧐', name: 'Face with Monocle' },
	{ emoji: '😕', name: 'Confused Face' },
	{ emoji: '😟', name: 'Worried Face' },
	{ emoji: '🙁', name: 'Slightly Frowning Face' },
	{ emoji: '☹️', name: 'Frowning Face' },
	{ emoji: '😮‍💨', name: 'Face Exhaling' },
	{ emoji: '😮‍💨', name: 'Face Exhaling' },
	{ emoji: '😮', name: 'Face with Open Mouth' },
	{ emoji: '😯', name: 'Hushed Face' },
	{ emoji: '😲', name: 'Astonished Face' },
	{ emoji: '😳', name: 'Flushed Face' },
	{ emoji: '🥺', name: 'Pleading Face' },
	{ emoji: '😦', name: 'Frowning Face with Open Mouth' },
	{ emoji: '😧', name: 'Anguished Face' },
	{ emoji: '😨', name: 'Fearful Face' },
	{ emoji: '😰', name: 'Anxious Face with Sweat' },
	{ emoji: '😥', name: 'Sad but Relieved Face' },
	{ emoji: '😢', name: 'Crying Face' },
	{ emoji: '😭', name: 'Loudly Crying Face' },
	{ emoji: '😱', name: 'Face Screaming in Fear' },
	{ emoji: '😖', name: 'Confounded Face' },
	{ emoji: '😣', name: 'Persevering Face' },
	{ emoji: '😞', name: 'Disappointed Face' },
	{ emoji: '😓', name: 'Downcast Face with Sweat' },
	{ emoji: '😩', name: 'Weary Face' },
	{ emoji: '😫', name: 'Tired Face' },
	{ emoji: '🥱', name: 'Yawning Face' },
	{ emoji: '😤', name: 'Face with Steam From Nose' },
	{ emoji: '😡', name: 'Pouting Face' },
	{ emoji: '😠', name: 'Angry Face' },
	{ emoji: '🤬', name: 'Face with Symbols on Mouth' },
	{ emoji: '😈', name: 'Smiling Face with Horns' },
	{ emoji: '👿', name: 'Angry Face with Horns' },
	{ emoji: '💀', name: 'Skull' },
	{ emoji: '☠️', name: 'Skull and Crossbones' },
	{ emoji: '💩', name: 'Pile of Poo' },
	{ emoji: '🤡', name: 'Clown Face' },
	{ emoji: '👹', name: 'Ogre' },
	{ emoji: '👺', name: 'Goblin' },
	{ emoji: '👻', name: 'Ghost' },
	{ emoji: '👽', name: 'Alien' },
	{ emoji: '🛸', name: 'Flying Saucer' },
	{ emoji: '😺', name: 'Grinning Cat' },
	{ emoji: '😸', name: 'Grinning Cat with Smiling Eyes' },
	{ emoji: '😹', name: 'Cat with Tears of Joy' },
	{ emoji: '😻', name: 'Smiling Cat with Heart-Eyes' },
	{ emoji: '😼', name: 'Cat with Wry Smile' },
	{ emoji: '😽', name: 'Kissing Cat' },
	{ emoji: '🙀', name: 'Weary Cat' },
	{ emoji: '😿', name: 'Crying Cat' },
	{ emoji: '😾', name: 'Pouting Cat' },
	{ emoji: '🐱', name: 'Cat Face' },
	{ emoji: '🐈', name: 'Cat' },
	{ emoji: '🐾', name: 'Paw Prints' },
	{ emoji: '🐶', name: 'Dog Face' },
	{ emoji: '🐕', name: 'Dog' },
	{ emoji: '🦮', name: 'Guide Dog' },
	{ emoji: '🐩', name: 'Poodle' },
	{ emoji: '🐺', name: 'Wolf' },
	{ emoji: '🦊', name: 'Fox' },
	{ emoji: '🦝', name: 'Raccoon' },
	{ emoji: '🐱‍👓', name: 'Cat with Monocle' },
	{ emoji: '🐱‍🚀', name: 'Cat Face with Astronaut' },
	{ emoji: '🦁', name: 'Lion' },
	{ emoji: '🐯', name: 'Tiger Face' },
	{ emoji: '🐅', name: 'Tiger' },
	{ emoji: '🐆', name: 'Leopard' },
	{ emoji: '🐴', name: 'Horse Face' },
	{ emoji: '🐎', name: 'Horse' },
	{ emoji: '🦄', name: 'Unicorn' },
	{ emoji: '🦓', name: 'Zebra' },
	{ emoji: '🦌', name: 'Deer' },
	{ emoji: '🐮', name: 'Cow Face' },
	{ emoji: '🐂', name: 'Ox' },
	{ emoji: '🐃', name: 'Water Buffalo' },
	{ emoji: '🐄', name: 'Cow' },
	{ emoji: '🐷', name: 'Pig Face' },
	{ emoji: '🐖', name: 'Pig' },
	{ emoji: '🐗', name: 'Boar' },
	{ emoji: '🐽', name: 'Pig Nose' },
	{ emoji: '🐏', name: 'Ram' },
	{ emoji: '🐑', name: 'Ewe' },
	{ emoji: '🐐', name: 'Goat' },
]
